# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  azurewebapptest:
    image: azurewebapptest
    build:
      context: .
      dockerfile: Azure Web App Test/Dockerfile
      args:
        - configuration=Debug
    ports:
      - 7172:7172
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
